ccflags-y += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_MACH_MSM8226_E7WIFI) += board-8226-e7wifi.o board-8226-e7wifi-gpiomux.o

CFLAGS_devices_lge.o += -Idrivers/staging/android
